In [1]:
import pandas as pd

# Cleaned BookRec_UserAgeToCountry.csv

In [4]:
# Load the dataset
df = pd.read_csv('../old/BookRec_UserAgeToCountry.csv')
display(df)

        User-ID                            Location   Age
0             1                  nyc, new york, usa   NaN
1             2           stockton, california, usa  18.0
2             3     moscow, yukon territory, russia   NaN
3             4           porto, v.n.gaia, portugal  17.0
4             5  farnborough, hants, united kingdom   NaN
...         ...                                 ...   ...
278853   278854               portland, oregon, usa   NaN
278854   278855  tacoma, washington, united kingdom  50.0
278855   278856           brampton, ontario, canada   NaN
278856   278857           knoxville, tennessee, usa   NaN
278857   278858                dublin, n/a, ireland   NaN

[278858 rows x 3 columns]

In [5]:
# Remove any records that do not have an age
df = df.dropna(subset=["Age"])
print(df.count)

<bound method DataFrame.count of         User-ID                            Location   Age
1             2           stockton, california, usa  18.0
3             4           porto, v.n.gaia, portugal  17.0
5             6       santa monica, california, usa  61.0
9            10          albacete, wisconsin, spain  26.0
10           11      melbourne, victoria, australia  14.0
...         ...                                 ...   ...
278848   278849         georgetown, ontario, canada  23.0
278850   278851                  dallas, texas, usa  33.0
278851   278852     brisbane, queensland, australia  32.0
278852   278853      stranraer, n/a, united kingdom  17.0
278854   278855  tacoma, washington, united kingdom  50.0

[168096 rows x 3 columns]>

In [ ]:
# Download the cleaned csv
df = pd.to_csv("../old/BookRec/Clean-BookRec_UserAgeToCountry_V2.csv")
display(df)

# Cleans 3 CSV files, connecting the readers's age by the genre
Prior to being added to this notebook, they have already been cleaned a bit by deleting unused columns

In [8]:
# Retrieve all the datasets as a dataframe
amazon_df = pd.read_csv("../old/BookRec/Amazon_TitleToGenre.csv")
booksToTitle_df = pd.read_excel("../old/BookRec/BookRec_BooksToTitle.xlsx")
userToBook_df = pd.read_excel("../old/BookRec/BookRec_UserToBook.xlsx")
userAge_df = pd.read_csv("../old/BookRec/Cleaned-BookRec_UserAgeToCountry.csv")

In [ ]:
display(amazon_df)
# display(booksToTitle_df)
# display(userToBook_df)
# display(userAge_df)

In [9]:
# Next start combining tables together, starting from the age table
merge_UserAge_UserToBook = pd.merge(userAge_df, userToBook_df, on="User-ID", how="inner")
display(merge_UserAge_UserToBook)

        Unnamed: 0  User-ID   Age     Country        ISBN
0                1        2  18.0         usa   195153448
1                9       10  26.0       spain  1841721522
2                9       10  26.0       spain  8477024456
3               18       19  14.0         NaN   375759778
4               19       20  19.0         usa   425163091
...            ...      ...   ...         ...         ...
764227      278850   278851  33.0         usa  1558531025
764228      278850   278851  33.0         usa  1566910102
764229      278850   278851  33.0         usa  1569661057
764230      278850   278851  33.0         usa  1885071213
764231      278851   278852  32.0   australia   449907597

[764232 rows x 5 columns]

In [10]:
# Next find the book title base on the ISBN numeber
merge_M1_BooksToTitle = pd.merge(merge_UserAge_UserToBook, booksToTitle_df, on="ISBN", how="inner")
display(merge_M1_BooksToTitle)

,Unnamed: 0,User-ID,Age,Country,ISBN,Title,Author,Year-Of-Publication
0,1,2,18.0,usa,195153448,Classical Mythology,Mark P. O. Morford,2002
1,9,10,26.0,spain,1841721522,New Vegetarian: Bold and Beautiful Recipes for...,Celia Brooks Brown,2001
2,18,19,14.0,NaN,375759778,Prague : A Novel,ARTHUR PHILLIPS,2003
3,19,20,19.0,usa,425163091,Chocolate Jesus,Stephan Jaramillo,1998
4,35,36,24.0,canada,067176537X,The Therapeutic Touch: How to Use Your Hands t...,Dolores Krieger,1979
...,...,...,...,...,...,...,...,...
685466,278850,278851,33.0,usa,1558531025,Life's Little Instruction Book (Life's Little ...,H. Jackson Brown,1991
685467,278850,278851,33.0,usa,1566910102,Oregon Handbook (The Americas Series),Stuart Warren,1995
685468,278850,278851,33.0,usa,1569661057,"Dallas Street Map Guide and Directory, 2000 Ed...",Mapsco,1999
685469,278850,278851,33.0,usa,1885071213,"Highpoint Adventures, A Pocket Guide to the 50...",Charlie Winger,1999
685470,278851,278852,32.0,australia,449907597,Dave Barry's Only Travel Guide You'll Ever Need,Dave Barry,1992

In [11]:
# Now use the book title to find the genre for each reader
# Rename the column since they do not match
merge_M1_BooksToTitle = merge_M1_BooksToTitle.rename(columns={'Book-Title' : 'Title'})
merge_M2_Amazon = pd.merge(merge_M1_BooksToTitle, amazon_df, on="Title", how="inner")
display(merge_M2_Amazon)

,Unnamed: 0_x,User-ID,Age,Country,ISBN,Title,Author_x,Year-Of-Publication,Unnamed: 0_y,Author_y,Main Genre,Sub Genre
0,253,254,24.0,usa,399501487,Lord of the Flies,William Gerald Golding,1959,734,William Golding,Children's Books,Crime & Thriller
1,253,254,24.0,usa,399501487,Lord of the Flies,William Gerald Golding,1959,7801,William Golding,Teen & Young Adult,Social & Family Issues
2,253,254,24.0,usa,440419468,Holes,LOUIS SACHAR,2003,730,Louis Sachar,Children's Books,Crime & Thriller
3,253,254,24.0,usa,440419468,Holes,LOUIS SACHAR,2003,7797,Louis Sachar,Teen & Young Adult,Social & Family Issues
4,383,384,23.0,romania,156528207,The Little Prince,Antoine de Saint-ExupÃƒÂ©ry,1968,862,Antoine De Saint-Exupéry,Children's Books,"Family, Personal & Social Issues"
...,...,...,...,...,...,...,...,...,...,...,...,...
3032,277638,277639,48.0,usa,553121456,Independence,Dana Fuller Ross,0,3331,Chitra Banerjee Divakaruni,Higher Education Textbooks,Social Sciences
3033,277763,277764,18.0,usa,399501487,Lord of the Flies,William Gerald Golding,1959,734,William Golding,Children's Books,Crime & Thriller
3034,277763,277764,18.0,usa,399501487,Lord of the Flies,William Gerald Golding,1959,7801,William Golding,Teen & Young Adult,Social & Family Issues
3035,278842,278843,28.0,usa,440477093,The Secret Garden,Frances H. Burnett,1990,671,Frances Hodgson Burnett,Children's Books,"Crafts, Hobbies & Practical Interests"
3036,278842,278843,28.0,usa,440477093,The Secret Garden,Frances H. Burnett,1990,3573,Frances Hodgson Burnett,Literature & Fiction,Classic Fiction

In [12]:
# Drop unused columns
cleaned_df = merge_M2_Amazon.drop(columns=['Unnamed: 0_x', 'Unnamed: 0_y'])
cleaned_df = cleaned_df.dropna()
display(cleaned_df)

,User-ID,Age,Country,ISBN,Title,Author_x,Year-Of-Publication,Author_y,Main Genre,Sub Genre
0,254,24.0,usa,399501487,Lord of the Flies,William Gerald Golding,1959,William Golding,Children's Books,Crime & Thriller
1,254,24.0,usa,399501487,Lord of the Flies,William Gerald Golding,1959,William Golding,Teen & Young Adult,Social & Family Issues
2,254,24.0,usa,440419468,Holes,LOUIS SACHAR,2003,Louis Sachar,Children's Books,Crime & Thriller
3,254,24.0,usa,440419468,Holes,LOUIS SACHAR,2003,Louis Sachar,Teen & Young Adult,Social & Family Issues
4,384,23.0,romania,156528207,The Little Prince,Antoine de Saint-ExupÃƒÂ©ry,1968,Antoine De Saint-Exupéry,Children's Books,"Family, Personal & Social Issues"
...,...,...,...,...,...,...,...,...,...,...
3032,277639,48.0,usa,553121456,Independence,Dana Fuller Ross,0,Chitra Banerjee Divakaruni,Higher Education Textbooks,Social Sciences
3033,277764,18.0,usa,399501487,Lord of the Flies,William Gerald Golding,1959,William Golding,Children's Books,Crime & Thriller
3034,277764,18.0,usa,399501487,Lord of the Flies,William Gerald Golding,1959,William Golding,Teen & Young Adult,Social & Family Issues
3035,278843,28.0,usa,440477093,The Secret Garden,Frances H. Burnett,1990,Frances Hodgson Burnett,Children's Books,"Crafts, Hobbies & Practical Interests"
3036,278843,28.0,usa,440477093,The Secret Garden,Frances H. Burnett,1990,Frances Hodgson Burnett,Literature & Fiction,Classic Fiction

In [13]:
# Since there seems to be a duplicate for each record, delete the duplicate
cleaned2_df = cleaned_df.drop_duplicates(subset=['User-ID', 'Title'])
display(cleaned2_df)

,User-ID,Age,Country,ISBN,Title,Author_x,Year-Of-Publication,Author_y,Main Genre,Sub Genre
0,254,24.0,usa,399501487,Lord of the Flies,William Gerald Golding,1959,William Golding,Children's Books,Crime & Thriller
2,254,24.0,usa,440419468,Holes,LOUIS SACHAR,2003,Louis Sachar,Children's Books,Crime & Thriller
4,384,23.0,romania,156528207,The Little Prince,Antoine de Saint-ExupÃƒÂ©ry,1968,Antoine De Saint-Exupéry,Children's Books,"Family, Personal & Social Issues"
7,882,23.0,usa,553255851,Where the Red Fern Grows,Wilson Rawls,1984,Wilson Rawls,Children's Books,Historical Fiction
8,1025,33.0,united kingdom,394404289,The Prophet,Kahlil Gibran,1973,Kahlil Gibran,Literature & Fiction,Classic Fiction
...,...,...,...,...,...,...,...,...,...,...
3030,277427,48.0,usa,553274295,Where the Red Fern Grows,Wilson Rawls,1984,Wilson Rawls,Children's Books,Historical Fiction
3031,277478,31.0,netherlands,425067645,Icebreaker,John Gardner,1984,HANNAH GRACE,Sports,Winter Sports
3032,277639,48.0,usa,553121456,Independence,Dana Fuller Ross,0,Chitra Banerjee Divakaruni,Higher Education Textbooks,Social Sciences
3033,277764,18.0,usa,399501487,Lord of the Flies,William Gerald Golding,1959,William Golding,Children's Books,Crime & Thriller
3035,278843,28.0,usa,440477093,The Secret Garden,Frances H. Burnett,1990,Frances Hodgson Burnett,Children's Books,"Crafts, Hobbies & Practical Interests"

In [ ]:
# Since the dataset of 1600 records is a bit too small, will need to check the age distributions
cleaned2_df["Age"].hist()

In [14]:
# Add Age labels to divide the data
# Ranges: 0-18 (Teens), 18-30 (Young Adult), 30-60 (Adult), 60-120 (Seniors) 
age_bins = [12, 18, 30, 60, 120]

age_groups = ["Teens (12-17)", "Young Adult (18-29)", "Adult (30-59)", "Senior (60+)"]

cleaned3_df = cleaned2_df.copy()

cleaned3_df["Age_Group"] = pd.cut(cleaned2_df["Age"], bins=age_bins, labels=age_groups, right=False)

display(cleaned3_df)

,User-ID,Age,Country,ISBN,Title,Author_x,Year-Of-Publication,Author_y,Main Genre,Sub Genre,Age_Group
0,254,24.0,usa,399501487,Lord of the Flies,William Gerald Golding,1959,William Golding,Children's Books,Crime & Thriller,Young Adult (18-29)
2,254,24.0,usa,440419468,Holes,LOUIS SACHAR,2003,Louis Sachar,Children's Books,Crime & Thriller,Young Adult (18-29)
4,384,23.0,romania,156528207,The Little Prince,Antoine de Saint-ExupÃƒÂ©ry,1968,Antoine De Saint-Exupéry,Children's Books,"Family, Personal & Social Issues",Young Adult (18-29)
7,882,23.0,usa,553255851,Where the Red Fern Grows,Wilson Rawls,1984,Wilson Rawls,Children's Books,Historical Fiction,Young Adult (18-29)
8,1025,33.0,united kingdom,394404289,The Prophet,Kahlil Gibran,1973,Kahlil Gibran,Literature & Fiction,Classic Fiction,Adult (30-59)
...,...,...,...,...,...,...,...,...,...,...,...
3030,277427,48.0,usa,553274295,Where the Red Fern Grows,Wilson Rawls,1984,Wilson Rawls,Children's Books,Historical Fiction,Adult (30-59)
3031,277478,31.0,netherlands,425067645,Icebreaker,John Gardner,1984,HANNAH GRACE,Sports,Winter Sports,Adult (30-59)
3032,277639,48.0,usa,553121456,Independence,Dana Fuller Ross,0,Chitra Banerjee Divakaruni,Higher Education Textbooks,Social Sciences,Adult (30-59)
3033,277764,18.0,usa,399501487,Lord of the Flies,William Gerald Golding,1959,William Golding,Children's Books,Crime & Thriller,Young Adult (18-29)
3035,278843,28.0,usa,440477093,The Secret Garden,Frances H. Burnett,1990,Frances Hodgson Burnett,Children's Books,"Crafts, Hobbies & Practical Interests",Young Adult (18-29)

In [ ]:
# Save the cleaned dataset
cleaned3_df.to_csv("../Combined_BookRec_GenreToAge.csv")

## Clean the Genres

In [20]:
read_df = pd.read_csv("../Combined_BookRec_GenreToAge.csv")
temp_df = pd.read_csv("../Combined_BookRec_GenreToAge_V2.csv")
display(read_df)

,User_ID,Age,Country,ISBN,Title,Author,Main_Genres,Genres,Age_Group
0,254,24,usa,399501487,Lord of the Flies,William Golding,Children's Books,Crime & Thriller,Young Adult (18-29)
1,254,24,usa,440419468,Holes,Louis Sachar,Children's Books,Crime & Thriller,Young Adult (18-29)
2,384,23,romania,156528207,The Little Prince,Antoine De Saint-Exupéry,Children's Books,"Family, Personal & Social Issues",Young Adult (18-29)
3,882,23,usa,553255851,Where the Red Fern Grows,Wilson Rawls,Children's Books,Historical Fiction,Young Adult (18-29)
4,1025,33,united kingdom,394404289,The Prophet,Kahlil Gibran,Literature & Fiction,Classic Fiction,Adult (30-59)
...,...,...,...,...,...,...,...,...,...
1677,277427,48,usa,553274295,Where the Red Fern Grows,Wilson Rawls,Children's Books,Historical Fiction,Adult (30-59)
1678,277478,31,netherlands,425067645,Icebreaker,HANNAH GRACE,Sports,Winter Sports,Adult (30-59)
1679,277639,48,usa,553121456,Independence,Chitra Banerjee Divakaruni,Higher Education Textbooks,Social Sciences,Adult (30-59)
1680,277764,18,usa,399501487,Lord of the Flies,William Golding,Children's Books,Crime & Thriller,Young Adult (18-29)
1681,278843,28,usa,440477093,The Secret Garden,Frances Hodgson Burnett,Children's Books,"Crafts, Hobbies & Practical Interests",Young Adult (18-29)

In [23]:
temp_df = pd.read_csv("../Combined_BookRec_GenreToAge_V2.csv")
table = pd.crosstab(temp_df['Country'], temp_df['Main_Genres'])

print(table)

Main_Genres         Arts, Film & Photography  \
Country
Australia                                  0
Austria                                    0
Belgium                                    0
Brazil                                     0
Canada                                     4
China                                      0
Denmark                                    2
Dominican Republic                         0
France                                     0
Germany                                    0
Haiti                                      0
Iran                                       0
Ireland                                    0
Italy                                      0
Japan                                      0
Malaysia                                   0
Netherlands                                0
New Zealand                                0
Norway                                     0
Philippines                                0
Poland                                     1
Portugal                                   0
Qatar                                      0
Romania                                    0
Singapore                                  0
South Africa                               0
Spain                                      1
Sweden                                     0
Switzerland                                0
Taiwan                                     1
United Kingdom                             3
United States                              8

Main_Genres         Biographies, Diaries & True Accounts  \
Country
Australia                                              1
Austria                                                0
Belgium                                                0
Brazil                                                 0
Canada                                                 1
China                                                  0
Denmark                                                0
Dominican Republic                                     0
France                                                 0
Germany                                                0
Haiti                                                  0
Iran                                                   0
Ireland                                                0
Italy                                                  0
Japan                                                  0
Malaysia                                               0
Netherlands                                            1
New Zealand                                            0
Norway                                                 0
Philippines                                            0
Poland                                                 0
Portugal                                               0
Qatar                                                  0
Romania                                                0
Singapore                                              0
South Africa                                           0
Spain                                                  0
Sweden                                                 0
Switzerland                                            0
Taiwan                                                 0
United Kingdom                                         0
United States                                         17

Main_Genres         Business & Economics  Children's Books  Comics & Mangas  \
Country
Australia                              2                 8                0
Austria                                0                 0                0
Belgium                                0                 0                0
Brazil                                 0                 0                0
Canada                                 1                53                0
China                                  0                 0                0
Denmark                                0                 0                0
Dominican Republic                     0                 1                0
France                                 0                 0                0
Germany                                2                 4                0
Haiti                                  0                 0                0
Iran                                   0                 2                0
Ireland                                0                 0                0
Italy                                  0                 5                0
Japan                                  0                 0                0
Malaysia                               1                10                0
Netherlands                            0                 0                1
New Zealand                            1                 0                0
Norway                                 0                 1                0
Philippines                            0                 0                0
Poland                                 0                 1                0
Portugal                               2                11                0
Qatar                                  0                 0                0
Romania                                0                 4                0
Singapore                              0                 1                0
South Africa                           0                 0                0
Spain                                  0                15                0
Sweden                                 0                 0                0
Switzerland                            0                 1                0
Taiwan                                 0                 0                0
United Kingdom                         2                29                0
United States                         22               440                2

Main_Genres         Computing, Internet & Digital Media  \
Country
Australia                                             0
Austria                                               0
Belgium                                               0
Brazil                                                0
Canada                                                6
China                                                 0
Denmark                                               0
Dominican Republic                                    0
France                                                1
Germany                                               0
Haiti                                                 0
Iran                                                  0
Ireland                                               0
Italy                                                 0
Japan                                                 0
Malaysia                                              0
Netherlands                                           0
New Zealand                                           0
Norway                                                0
Philippines                                           1
Poland                                                0
Portugal                                              0
Qatar                                                 0
Romania                                               0
Singapore                                             0
South Africa                                          0
Spain                                                 0
Sweden                                                1
Switzerland                                           0
Taiwan                                                0
United Kingdom                                        0
United States                                        52

Main_Genres         Crafts, Home & Lifestyle  Crime, Thriller & Mystery  \
Country
Australia                                  1                          7
Austria                                    0                          1
Belgium                                    0                          0
Brazil                                     2                          0
Canada                                     1                         10
China                                      0                          1
Denmark                                    0                          0
Dominican Republic                         0                          0
France                                     0                          0
Germany                                    0                          1
Haiti                                      0                          0
Iran                                       0                          0
Ireland                                    0                          0
Italy                                      0                          0
Japan                                      0                          1
Malaysia                                   0                          4
Netherlands                                1                          2
New Zealand                                0                          1
Norway                                     0                          1
Philippines                                0                          0
Poland                                     0                          0
Portugal                                   0                          0
Qatar                                      0                          0
Romania                                    0                          0
Singapore                                  0                          0
South Africa                               0                          0
Spain                                      0                          1
Sweden                                     0                          0
Switzerland                                0                          0
Taiwan                                     0                          0
United Kingdom                             2                          7
United States                             18                         75

Main_Genres         Fantasy, Horror & Science Fiction  \
Country
Australia                                           0
Austria                                             0
Belgium                                             0
Brazil                                              0
Canada                                              9
China                                               0
Denmark                                             0
Dominican Republic                                  0
France                                              2
Germany                                             0
Haiti                                               1
Iran                                                0
Ireland                                             0
Italy                                               0
Japan                                               0
Malaysia                                            0
Netherlands                                         1
New Zealand                                         0
Norway                                              0
Philippines                                         0
Poland                                              0
Portugal                                            1
Qatar                                               0
Romania                                             0
Singapore                                           0
South Africa                                        0
Spain                                               5
Sweden                                              0
Switzerland                                         0
Taiwan                                              0
United Kingdom                                      3
United States                                      71

Main_Genres         Higher Education Textbooks  ...  \
Country                                         ...
Australia                                    0  ...
Austria                                      0  ...
Belgium                                      0  ...
Brazil                                       0  ...
Canada                                       0  ...
China                                        0  ...
Denmark                                      0  ...
Dominican Republic                           0  ...
France                                       0  ...
Germany                                      0  ...
Haiti                                        0  ...
Iran                                         0  ...
Ireland                                      0  ...
Italy                                        0  ...
Japan                                        0  ...
Malaysia                                     0  ...
Netherlands                                  0  ...
New Zealand                                  0  ...
Norway                                       0  ...
Philippines                                  0  ...
Poland                                       0  ...
Portugal                                     0  ...
Qatar                                        0  ...
Romania                                      0  ...
Singapore                                    0  ...
South Africa                                 0  ...
Spain                                        0  ...
Sweden                                       0  ...
Switzerland                                  0  ...
Taiwan                                       0  ...
United Kingdom                               0  ...
United States                                9  ...

Main_Genres         Medicine & Health Sciences  Reference  Religion  Romance  \
Country
Australia                                    0          0         1        5
Austria                                      0          0         0        0
Belgium                                      0          0         0        0
Brazil                                       0          0         0        0
Canada                                       0          6         6       18
China                                        0          0         0        0
Denmark                                      0          0         0        0
Dominican Republic                           0          1         0        0
France                                       0          1         1        0
Germany                                      0          1         0        0
Haiti                                        0          0         0        0
Iran                                         0          1         0        0
Ireland                                      0          0         0        0
Italy                                        0          0         0        2
Japan                                        0          0         0        0
Malaysia                                     0          0         0        1
Netherlands                                  0          0         0        1
New Zealand                                  0          0         0        0
Norway                                       0          0         0        0
Philippines                                  0          0         0        0
Poland                                       0          0         0        1
Portugal                                     0          1         0        1
Qatar                                        0          1         0        0
Romania                                      0          0         2        0
Singapore                                    0          0         1        1
South Africa                                 0          0         0        1
Spain                                        0          0         1        1
Sweden                                       0          0         0        0
Switzerland                                  0          0         0        0
Taiwan                                       0          0         0        0
United Kingdom                               0          1         0        3
United States                                7         46        43      138

Main_Genres         Science & Mathematics  Sciences, Technology & Medicine  \
Country
Australia                               1                                1
Austria                                 0                                0
Belgium                                 0                                0
Brazil                                  0                                0
Canada                                  2                                2
China                                   0                                0
Denmark                                 0                                0
Dominican Republic                      0                                0
France                                  0                                0
Germany                                 0                                0
Haiti                                   0                                0
Iran                                    0                                0
Ireland                                 0                                0
Italy                                   0                                0
Japan                                   0                                0
Malaysia                                0                                0
Netherlands                             0                                1
New Zealand                             0                                0
Norway                                  0                                0
Philippines                             0                                0
Poland                                  1                                0
Portugal                                0                                1
Qatar                                   0                                0
Romania                                 0                                0
Singapore                               0                                0
South Africa                            0                                0
Spain                                   0                                0
Sweden                                  0                                0
Switzerland                             0                                0
Taiwan                                  0                                0
United Kingdom                          0                                0
United States                           9                               32

Main_Genres         Society & Social Sciences  Sports  Teen & Young Adult  \
Country
Australia                                   0       1                   0
Austria                                     0       0                   0
Belgium                                     1       0                   0
Brazil                                      0       0                   0
Canada                                      2      11                   0
China                                       1       0                   0
Denmark                                     0       0                   0
Dominican Republic                          0       0                   0
France                                      0       0                   0
Germany                                     0       0                   1
Haiti                                       0       0                   0
Iran                                        0       0                   0
Ireland                                     0       0                   0
Italy                                       0       0                   0
Japan                                       0       0                   0

In [24]:
# Get the list of genres
unique_genres = set()

# Loop through all the records' genre
for record in temp_df['Main_Genres']:
    unique_genres.add(record)
    
display(unique_genres)

{'Arts, Film & Photography',
 'Biographies, Diaries & True Accounts',
 'Business & Economics',
 "Children's Books",
 'Comics & Mangas',
 'Computing, Internet & Digital Media',
 'Crafts, Home & Lifestyle',
 'Crime, Thriller & Mystery',
 'Fantasy, Horror & Science Fiction',
 'Higher Education Textbooks',
 'History',
 'Literature & Fiction',
 'Medicine & Health Sciences',
 'Reference',
 'Religion',
 'Romance',
 'Science & Mathematics',
 'Sciences, Technology & Medicine',
 'Society & Social Sciences',
 'Sports',
 'Teen & Young Adult',
 'Travel'}

In [30]:
flat_map = {
    "fantasy": "Fantasy", "dark fantasy": "Fantasy", "magical realism": "Fantasy", "fable": "Fantasy", "parable": "Fantasy",
    "fantasy, horror & science fiction": "Fantasy", # Mapped to your existing 'Fantasy'

    "sci-fi": "Sci-Fi", "dystopian": "Sci-Fi", "cyberpunk": "Sci-Fi", "steampunk": "Sci-Fi", "detective sci-fi": "Sci-Fi", "post-apocalyptic": "Sci-Fi",

    "mystery": "Mystery/Thriller", "thriller": "Mystery/Thriller", "crime": "Mystery/Thriller", "mystery-thriller": "Mystery/Thriller", 
    "detective": "Mystery/Thriller", "legal thriller": "Mystery/Thriller", "techno-thriller": "Mystery/Thriller", "spy fiction": "Mystery/Thriller", "true crime": "Mystery/Thriller",
    "crime, thriller & mystery": "Mystery/Thriller",

    "romance": "Romance", "historical romance": "Romance",

    "children's fiction": "Children", "children's books": "Children",

    "young adult": "Young Adult", "coming-of-age": "Young Adult", "bildungsroman": "Young Adult", "teen & young adult": "Young Adult",

    "non-fiction": "Non-Fiction", "history": "Non-Fiction", "biography": "Non-Fiction", "autobiography": "Non-Fiction", "memoir": "Non-Fiction", 
    "economics": "Non-Fiction", "philosophy": "Non-Fiction", "psychology": "Non-Fiction", "science": "Non-Fiction", "business": "Non-Fiction", 
    "self-help": "Non-Fiction", "finance": "Non-Fiction", "gonzo journalism": "Non-Fiction", "feminist non-fiction": "Non-Fiction",
    "biographies, diaries & true accounts": "Non-Fiction", "business & economics": "Non-Fiction", "society & social sciences": "Non-Fiction",
    "religion": "Non-Fiction", "science & mathematics": "Non-Fiction", "sciences, technology & medicine": "Non-Fiction",
    "computing, internet & digital media": "Non-Fiction", "medicine & health sciences": "Non-Fiction",
    "higher education textbooks": "Non-Fiction", "reference": "Non-Fiction",

    "historical fiction": "Historical Fiction", "alternate history": "Historical Fiction", "historiographic metafiction": "Historical Fiction",

    "graphic novel": "Graphic Novels/Manga", "graphic memoir": "Graphic Novels/Manga", "comics & mangas": "Graphic Novels/Manga",

    "art": "Art/Literature", "poetry": "Art/Literature", "epic poetry": "Art/Literature", "drama": "Art/Literature", "play": "Art/Literature", 
    "classic": "Art/Literature", "literary fiction": "Art/Literature", "fiction": "Art/Literature", "contemporary fiction": "Art/Literature", 
    "feminist fiction": "Art/Literature", "social novel": "Art/Literature", "political fiction": "Art/Literature", "psychological fiction": "Art/Literature",
    "tragedy": "Art/Literature", "realism": "Art/Literature", "modernist": "Art/Literature", "epistolary": "Art/Literature", "metafiction": "Art/Literature",
    "absurdist": "Art/Literature", "allegory": "Art/Literature", "beat": "Art/Literature", "dark academia": "Art/Literature", "transgressive": "Art/Literature",
    "arts, film & photography": "Art/Literature", "literature & fiction": "Art/Literature",

    "humor": "Humor", "satire": "Humor",

    "short stories": "Short Stories", "novella": "Short Stories",

    "horror": "Horror", "gothic horror": "Horror", "historical horror": "Horror", "gothic": "Horror", "southern gothic": "Horror",

    "adventure": "Adventure", "western": "Adventure", "picaresque": "Adventure", "war": "Adventure", "sports": "Adventure", "travel": "Adventure",
    "crafts, home & lifestyle": "Adventure" # Assigned to Adventure or you can use "Non-Fiction"
}

In [44]:
# Grab the GetGeneralGenres function again 

def GetGeneralGenres(word):
    # print(word)
    
    word = word.lower().strip()
    if word in flat_map:
        # print(word)
        genre = flat_map[word] 
        
        # Return a list of general genres
        return genre
    return ""

In [45]:
# Grab a coopy of the map_df and then apply the general genres
temp_copy_df = temp_df.copy()
temp_copy_df['Main_Genres'] = temp_copy_df['Main_Genres'].apply(GetGeneralGenres)
display(temp_copy_df)

,Unnamed: 0,User_ID,Age,Country,ISBN,Title,Author,Main_Genres,Genres,Age_Group
0,0,254,24,United States,399501487,Lord of the Flies,William Golding,Children,Crime & Thriller,Young Adult (18-29)
1,1,254,24,United States,440419468,Holes,Louis Sachar,Children,Crime & Thriller,Young Adult (18-29)
2,2,384,23,Romania,156528207,The Little Prince,Antoine De Saint-Exupéry,Children,"Family, Personal & Social Issues",Young Adult (18-29)
3,3,882,23,United States,553255851,Where the Red Fern Grows,Wilson Rawls,Children,Historical Fiction,Young Adult (18-29)
4,4,1025,33,United Kingdom,394404289,The Prophet,Kahlil Gibran,Art/Literature,Classic Fiction,Adult (30-59)
...,...,...,...,...,...,...,...,...,...,...
1677,1677,277427,48,United States,553274295,Where the Red Fern Grows,Wilson Rawls,Children,Historical Fiction,Adult (30-59)
1678,1678,277478,31,Netherlands,425067645,Icebreaker,HANNAH GRACE,Adventure,Winter Sports,Adult (30-59)
1679,1679,277639,48,United States,553121456,Independence,Chitra Banerjee Divakaruni,Non-Fiction,Social Sciences,Adult (30-59)
1680,1680,277764,18,United States,399501487,Lord of the Flies,William Golding,Children,Crime & Thriller,Young Adult (18-29)
1681,1681,278843,28,United States,440477093,The Secret Garden,Frances Hodgson Burnett,Children,"Crafts, Hobbies & Practical Interests",Young Adult (18-29)

In [46]:
temp_copy_df.to_csv("../Combined_BookRec_GenreToAge_V3.csv")